"""add records,categories,user models

Revision ID: 1531b1b8c3ea
Revises: cdc7ccd1d11c
Create Date: 2023-05-16 20:26:53.217633

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "1531b1b8c3ea"
down_revision = "cdc7ccd1d11c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "income_category",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "outcome_category",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "user",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("tg_id", sa.BigInteger(), nullable=True),
        sa.Column("first_name", sa.String(length=64), nullable=True),
        sa.Column("last_name", sa.String(length=64), nullable=True),
        sa.Column("tg_username", sa.String(length=32), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tg_id"),
    )
    op.create_table(
        "income",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.Column("created_on", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.CheckConstraint("amount >= 0.00", name="income_amount_positive"),
        sa.CheckConstraint(
            "created_on >= CURRENT_TIMESTAMP", name="income_created_on_positive"
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["income_category.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "outcome",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.Column("created_on", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.CheckConstraint("amount >= 0.00", name="outcome_amount_positive"),
        sa.CheckConstraint(
            "created_on >= CURRENT_TIMESTAMP", name="outcome_created_on_positive"
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["outcome_category.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("outcome")
    op.drop_table("income")
    op.drop_table("user")
    op.drop_table("outcome_category")
    op.drop_table("income_category")
    # ### end Alembic commands ###
