"""delete created_on_posotive constrain

Revision ID: 373179b930e1
Revises: 1531b1b8c3ea
Create Date: 2023-05-20 19:14:30.946603

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "373179b930e1"
down_revision = "1531b1b8c3ea"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("outcome_created_on_positive", "outcome")
    op.drop_constraint("income_created_on_positive", "income")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(
        "outcome_created_on_positive",
        "outcome",
        "created_on >= CURRENT_TIMESTAMP",
    )
    op.create_check_constraint(
        "income_created_on_positive",
        "income",
        "created_on >= CURRENT_TIMESTAMP",
    )
    # ### end Alembic commands ###
